@HotelAPIMiddleware_HostAddress = http://localhost:5073

GET {{HotelAPIMiddleware_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{HotelAPIMiddleware_HostAddress}}/api/hotel/booling-prep
Content-Type: application/json

{
  "provider": "STUBA",
  "data": {
    "cacheId": "hotel_search_cache_203c7546-c7bd-484e-bb1c-e3caf8902c26_20260227050356",
    "searchId": "203c7546-c7bd-484e-bb1c-e3caf8902c26",
    "hotelId": "hotel_ce51d0d5-bde3-4021-ad47-8856837850f4",
    "quoteId": "1090488613-839"
  }
}

###

POST {{HotelAPIMiddleware_HostAddress}}/api/hotel/booling-prep
Content-Type: application/json

{
  "provider": "RateHawk",
  "data": {
    "hid": "13649126",
    "checkIn": "2026-03-25",
    "checkOut": "2026-03-26",
    "residency": "ae",
    "language": "en",
    "currency": "USD",
    "guests": [
      {
        "adults": 2,
        "children": []
      }
    ],
    "priceIncreasePercent": 20
  }
}

###
